### ISSUE TITLE
`set-output` command deprecation

### ISSUE THREAD

**Issue by HardNorth** [mindsers/changelog-reader-action#75]
Hi!
Thanks for the useful action. Unfortunately lately we started getting this warning:
> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Could you please update your `@actions/core` dependency to at least version `1.10.0`.
Thank you!

**Comment by mindsers** [comment]
Should be fixed by v2.2.1

**Comment by guihkx** [comment]
Hello @mindsers, I'm still seeing these warnings with `2.2.1`:

![image](https://user-images.githubusercontent.com/626206/201927803-701ab2e6-d421-4f1d-8e00-d7052d605827.png)

Any clues?

**Comment by guihkx** [comment]
(Aside: The README claims `validation_depth` is set to `0` by default, but in the screenshot above it's set to `10` and I haven't configured it).

**Comment by HardNorth** [comment]
Agree, I'm seeing the same issue. For some reason compiled version of the action has not changed:
https://github.com/mindsers/changelog-reader-action/blob/master/dist/index.js#L2878
```javascript
function setOutput(name, value) {
    process.stdout.write(os.EOL);
    command_1.issueCommand('set-output', { name }, value);
}
```

**Comment by mindsers** [comment]
Looking. Weird that the built version didn't change. I'll publish a new version with the fix soon.
